"""Constants related to JWT handling."""

AUTHZ_CODE = "authorizationCode"
AUTHZ_ENDPOINT = "authorization_endpoint"
ISSUER = "issuer"
CODE = "code"
ID_TOKEN = "id_token"
ACCESS_TOKEN = "access_token"
REFRESH_TOKEN = "refresh_token"
SCOPE = "scope"
REDIR_URI = "redirect_uri"
NONCE = "nonce"
STATE = "state"
RES_TYPE = "response_type"
CLIENT_ID = "client_id"
CONSENT = "consent"
CONSENT_SCOPES = "consentedScopes"
