"""Constants used in Car classes"""

HOMEREGION = "homeRegion"
BASEURI = "baseUri"
CONTENT = "content"

# Attributes
CHARGER = "CHARGING"
AIRCON = "AIR_CONDITIONING"
ACCESS = "ACCESS"
FUEL = "FUEL_STATUS"
MEASUREMENTS = "MEASUREMENTS"
POSITION = "PARKING_POSITION"
STATE = "STATE"
LIGHTS = "VEHICLE_LIGHTS"
